promptToReturnFromSubprocess: false
gui:
  mainPanelSplitMode: 'vertical'
  sidePanelWidth: 0.20
  commandLogSize: 1
  theme:
    selectedLineBgColor:
      - '#3d3d3d'

git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
  allBranchesLogCmd: 'git log --graph --abbrev-commit --decorate --format=tformat:"%C(yellow)%h%C(reset)%C(reset)%C(auto)%d%C(reset) %s %C(white) -  %C(bold green)(%ar)%C(reset) %C(dim blue)<%an>%Creset"'
  commit:
    autoWrapCommitMessage: false
  paging:
    colorArg: always
    useConfig: true

keybinding:
  universal:
    copyToClipboard: 'y'
    nextBlock-alt: '<right>'
    nextScreenMode: '+'
    nextTab: 'l'
    openRecentRepos: ''
    prevBlock-alt: '<left>'
    prevScreenMode: '-'
    prevTab: 'h'
    redo: '<c-r>'
    undo: 'u'
  commits:
    amendToCommit: 'a'
    cherryPickCopy: '<c-y>'
    copyCommitAttributeToClipboard: 'Y'
    pasteCommits: '<c-p>'
