#!/bin/bash

temperature="$(sensors | awk '/^Core/{gsub(/[°C+]/,"",$3); s+=$3; c++} END {print s/c}')"
max_temp="$(sensors | awk '/^Core/{gsub(/[°C+,]/,"",$6); s+=$6; c++} END{print s/c}')"

if (($(echo "$temperature < 45" | bc -l))); then
	label='🥶'
elif (($(echo "$temperature < 65" | bc -l))); then
	label='😎'
elif (($(echo "$temperature < 85" | bc -l))); then
	label='🌡️'
elif (($(echo "$temperature < $max_temp" | bc -l))); then
	label='🥵'
else
	label='🔥'
fi

echo "${label} ${temperature}°C"
exit 0
