alias basev="nvim -u ~/.config/nvim/base-init.lua"
alias bigv="nvim -u ~/.config/nvim/big-init.lua"
alias v="nvim"
alias vo=fzf_nvim; fzf_nvim() { nvim "$(fzf)" }
alias voa="cd ~/dotfiles/ && nvim ~/dotfiles/zsh/.config/zsh/aliases/init.zsh"
alias voi="cd ~/dotfiles/ && nvim ~/dotfiles/i3/.config/i3/config"
alias vov="cd ~/dotfiles/nvim/.config/nvim/ && nvim init.lua"
alias voz="cd ~/dotfiles/ && nvim ~/dotfiles/zsh/.config/zsh/env_vars.zsh"
alias ncurl='nvim -c "CurlOpen global" -c "tabonly"'
alias remv=remote_nvim; remote_nvim() { nvim scp://"$1"//"$2" }
